"""empty message

Revision ID: ce125f9cbfe1
Revises: 
Create Date: 2023-08-19 20:39:36.784309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce125f9cbfe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=20, scale=4), nullable=False),
    sa.Column('period', postgresql.TSRANGE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='payments'
    )
    op.create_index('ix_currency_code', 'currency', ['code'], unique=False, schema='payments')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currency_code', table_name='currency', schema='payments')
    op.drop_table('currency', schema='payments')
    # ### end Alembic commands ###
